#!/bin/bash
readonly SWANK_LOCATION=personal/swank-racket
readonly RACKET_EXECUTABLE=/Users/16676965/personal/Racket\ v8.6/bin/racket
cd ${SWANK_LOCATION} && "$RACKET_EXECUTABLE" server.rkt &
# run terminal emulator
# ..with zsh
# ..starting nvim
# ..with custom vim startup arguments
# ..passing script args to vim
arg=$@
alacritty \
-e zsh \
-c "nvim \
-c ':call AutoHighlightToggle()' -c 'set hls' \
-c ':call SlimvConnectServer()' \
${arg}"
