#!/bin/bash
# run terminal emulator
# ..with zsh
# ..starting nvim
# ..with custom vim startup arguments
# ..passing script args to vim
arg=$@
open /Applications/Alacritty.app \
--args \
-e zsh \
-c "/Users/16676965/Downloads/nvim-macos/bin/nvim \
-c ':call AutoHighlightToggle()' -c 'set hls' \
${arg}"
