#!/bin/bash
# run terminal emulator
# ..with zsh
# ..starting nvim
# ..with custom vim startup arguments
# ..passing script args to vim
arg=$@
open /Applications/Alacritty.app \
--args \
-e zsh \
-c "nvim -u ~/.config/nvim/lisp-ide-init.vim \
-c ':call AutoHighlightToggle()' -c 'set hls' \
${arg}"
